import {
  ActivitySquare,
  BarChart3,
  Bell,
  BookOpen,
  Calendar,
  Church,
  Database,
  DollarSign,
  FileText,
  Heart,
  Home,
  Image as ImageIcon,
  MapPin,
  MessageCircle,
  Settings,
  Shield,
  Smartphone,
  Upload,
  UserCheck,
  Users,
  Webhook,
} from 'lucide-react'

export const superAdminControlSections = [
  {
    id: 'dashboards',
    title: 'Dashboards',
    description: 'Move across the role-specific dashboards available in the system.',
    icon: Shield,
    items: [
      { label: 'Super Admin', description: 'Open the top-level command center.', path: '/admin-dashboard', icon: Shield },
      { label: 'Pastor Dashboard', description: 'View executive reporting and church oversight.', path: '/pastor-dashboard', icon: Church },
      { label: 'Member Dashboard', description: 'Check the regular member experience.', path: '/dashboard', icon: Home },
      { label: 'Mobile Dashboard', description: 'Inspect the mobile app dashboard flow.', path: '/mobile/dashboard', icon: Smartphone },
      { label: 'Sunday Check-in', description: 'Run or monitor usher attendance check-in.', path: '/checkin', icon: UserCheck },
    ],
  },
  {
    id: 'people-structure',
    title: 'People & Structure',
    description: 'Manage members, permissions, assignments, cells, and zones.',
    icon: Users,
    items: [
      { label: 'Members', description: 'Open the full member directory.', path: '/members', icon: Users },
      { label: 'Add Member', description: 'Create new user and leadership records.', path: '/members/add', icon: UserCheck },
      { label: 'Permissions', description: 'Change roles across the platform.', path: '/permissions', icon: Shield },
      { label: 'Assignments', description: 'Manage leadership hierarchy and placements.', path: '/pastor/assignments', icon: Shield },
      { label: 'Zones', description: 'Control zone structure and leadership.', path: '/pastor/zones', icon: MapPin },
      { label: 'Zone Dashboard', description: 'Inspect the zone leader workspace.', path: '/zone/dashboard', icon: MapPin },
      { label: 'Cell Dashboard', description: 'Inspect the cell leader workspace.', path: '/cell/dashboard', icon: Home },
      { label: 'Zone Members', description: 'Review members grouped under each zone.', path: '/zone/members', icon: Users },
      { label: 'Zone Cells', description: 'Review and manage cell group structure.', path: '/zone/cells', icon: Home },
      { label: 'Cell Requests', description: 'Approve or reject member cell changes.', path: '/leadership/cell-change-requests', icon: Bell },
    ],
  },
  {
    id: 'ministry-ops',
    title: 'Ministry & Operations',
    description: 'Oversee events, care, communication, giving, and daily operations.',
    icon: ActivitySquare,
    items: [
      { label: 'Announcements', description: 'Create and manage church announcements.', path: '/announcements', icon: Bell },
      { label: 'Prayer', description: 'Review prayer requests and follow-up needs.', path: '/prayer', icon: Heart },
      { label: 'Chat', description: 'Oversee rooms, groups, and conversations.', path: '/chat', icon: MessageCircle },
      { label: 'Events', description: 'Manage the full event calendar.', path: '/events', icon: Calendar },
      { label: 'Create Event', description: 'Publish new church events directly.', path: '/events/create', icon: Calendar },
      { label: 'Leadership', description: 'Inspect the leadership operations page.', path: '/leadership', icon: Shield },
      { label: 'Pastoral Care', description: 'Handle care and follow-up workflows.', path: '/pastoral-care', icon: Heart },
      { label: 'Volunteers', description: 'Track serving teams and volunteers.', path: '/volunteers', icon: Users },
      { label: 'Giving', description: 'Review member giving records.', path: '/giving', icon: DollarSign },
      { label: 'Donations', description: 'Inspect donation activity and finance views.', path: '/donations', icon: DollarSign },
    ],
  },
  {
    id: 'content-media',
    title: 'Content & Media',
    description: 'Control sermons, blog publishing, bible resources, and homepage images.',
    icon: FileText,
    items: [
      { label: 'Sermons', description: 'Manage sermon content and media.', path: '/sermons', icon: BookOpen },
      { label: 'Sermon Manager', description: 'Edit, publish, and remove sermon uploads.', path: '/sermons/manage', icon: FileText },
      { label: 'Sermon Prep', description: 'Prepare sermon drafts and notes.', path: '/sermons/prepare', icon: FileText },
      { label: 'Upload Sermon', description: 'Upload sermon media assets.', path: '/sermons/upload', icon: Upload },
      { label: 'Blog Manager', description: 'Control published and draft blog posts.', path: '/blog/manage', icon: FileText },
      { label: 'Create Blog Post', description: 'Publish new blog content.', path: '/blog/create', icon: FileText },
      { label: 'Home Images', description: 'Post and maintain website images.', path: '/admin/home-images', icon: ImageIcon },
      { label: 'Bible', description: 'Inspect the public Bible experience.', path: '/bible', icon: BookOpen },
    ],
  },
  {
    id: 'analytics-system',
    title: 'Analytics & System',
    description: 'Track reports, attendance, settings, APIs, and integrations.',
    icon: BarChart3,
    items: [
      { label: 'Analytics', description: 'View reporting and church metrics.', path: '/analytics', icon: BarChart3 },
      { label: 'Attendance History', description: 'Review historical attendance records.', path: '/attendance/history', icon: ActivitySquare },
      { label: 'Settings', description: 'Update platform and church configuration.', path: '/settings', icon: Settings },
      { label: 'API Keys', description: 'Control developer API access.', path: '/developers/api-keys', icon: Database },
      { label: 'Webhooks', description: 'Configure outbound system webhooks.', path: '/developers/webhooks', icon: Webhook },
      { label: 'API Analytics', description: 'Inspect API traffic and usage trends.', path: '/developers/analytics', icon: BarChart3 },
      { label: 'Integrations', description: 'Connect or manage external services.', path: '/developers/integrations', icon: Database },
      { label: 'API Docs', description: 'Open the developer documentation.', path: '/api-docs', icon: BookOpen },
    ],
  },
]

export const superAdminQuickActions = [
  { label: 'Members', description: 'Jump straight to member management.', path: '/members', icon: Users, color: 'bg-blue-50 text-blue-600' },
  { label: 'Permissions', description: 'Promote, demote, or reassign roles.', path: '/permissions', icon: Shield, color: 'bg-purple-50 text-purple-600' },
  { label: 'Home Images', description: 'Post and replace website images.', path: '/admin/home-images', icon: ImageIcon, color: 'bg-emerald-50 text-emerald-600' },
  { label: 'Chat Groups', description: 'Create and moderate church chat rooms.', path: '/chat', icon: MessageCircle, color: 'bg-orange-50 text-orange-600' },
  { label: 'API Access', description: 'Control API keys, analytics, and webhooks.', path: '/developers/api-keys', icon: Database, color: 'bg-slate-100 text-slate-700' },
  { label: 'Settings', description: 'Update system-wide configuration.', path: '/settings', icon: Settings, color: 'bg-amber-50 text-amber-600' },
]

export const totalSuperAdminControls = superAdminControlSections.reduce(
  (total, section) => total + section.items.length,
  0
)
