CREATE TABLE IF NOT EXISTS member_email_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    member_id INT NULL,
    sent_by INT NULL,
    recipient_email VARCHAR(255) NOT NULL,
    recipient_name VARCHAR(255),
    recipient_type VARCHAR(50) DEFAULT 'member',
    subject VARCHAR(255) NOT NULL,
    html_body LONGTEXT,
    text_body LONGTEXT,
    email_type VARCHAR(100) DEFAULT 'follow_up',
    source VARCHAR(100) DEFAULT 'manual',
    status VARCHAR(20) DEFAULT 'sent',
    related_absence_flag_id INT NULL,
    related_follow_up_note_id INT NULL,
    queue_id INT NULL,
    error_message TEXT,
    sent_at DATETIME NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_member_email_logs_member (member_id),
    INDEX idx_member_email_logs_sent_by (sent_by),
    INDEX idx_member_email_logs_status (status),
    INDEX idx_member_email_logs_created_at (created_at),
    INDEX idx_member_email_logs_sent_at (sent_at),
    INDEX idx_member_email_logs_source (source),
    INDEX idx_member_email_logs_recipient_type (recipient_type),
    FOREIGN KEY (member_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (sent_by) REFERENCES users(id) ON DELETE SET NULL
);
